### PR TITLE
feat: add typeorm support ^0.3.0

### PR DESCRIPTION
**Pull request by rpvsilva**
Since there is no response from #34 I've pulled the changes from @dominicbachmann and rebased with `master`, the tests are passing also. Also, I've upgraded the MySQL client version to 2 to test with MySQL v8 and it's working.

### CODE REVIEW

**Comment by jspizziri** [comment]
@bashleigh would love to see typeorm 0.3.0 support added to this lib.

Thanks!

**Comment by jspizziri** [comment]
@rpvsilva you haven't published your fork have you?

**Comment by jspizziri** [comment]
After looking more closely at this PR, I've decided to submit a different approach to this upgrade.

Please see https://github.com/bashleigh/typeorm-polymorphic/pull/38 which explains the motivation.

**Comment by rpvsilva** [comment]
Closing PR because of #38

**Pull request closed without merging**
