### PR TITLE
feat(typeorm): upgrade typeorm to v0.3 and address breaking changes

### PR DESCRIPTION
**Pull request by jspizziri**
typeorm intorduced several breaking changes in v0.3.0. this refactors the library to account for those changes. specifically some changes to the repository interface and the removal of the ability to fetch a custom repository.

BREAKING CHANGE: `EntityRepository` is replaced with `PolymorphicRepository`. `connection.getCustomRepository` is replaced with `AbstractPolymorphicRepository.createRepository`.

### CODE REVIEW

**Comment by jspizziri** [comment]
This PR is based off of the work done here (https://github.com/bashleigh/typeorm-polymorphic/pull/37 & https://github.com/bashleigh/typeorm-polymorphic/pull/34).

What's the motivation:

1. I believe this method is "less" breaking than the others, which will make it easier for users to adopt (it certainly does for me).
2. It hides some of the implementation details of extending repositories from the end user.

My specific use-case:

I have a legacy project and want to change as little as possible. In addition, I have `AbstractPolymorphicRepository`'s that introduce their own methods like so:

```ts
export class AdvertRepository extends AbstractPolymorphicRepository<AdvertEntity> {
    getFoo(): string {
        return 'foo';
    }
}
```

In order to accomplish this same thing with the other PR's it's a little more messy. I'd need to either wrap the `createPolymorphicRepository` and spread it's return across my own return object, or I'd need to do multiple extensions of the baseRepository in typeorm (e.g.  `const repository = baseRepository.extend([polymorphic]).extend([other stuff]);`), the last of which doesn't work very well.

Furthermore, and this may be the most specific thing to me, is that I use this project in the context of `nestjs`, and this method allows for an easier implementation of dependency injection within that context.

**Comment by bashleigh** [comment]
Thanks! Looks great!

**Comment by jspizziri** [comment]
@bashleigh would you be able to cut a new release and publish to npm?

**Comment by bashleigh** [comment]
sorry, been so so busy :( depoyed as v1.0.0

**Comment by jspizziri** [comment]
Thank you!

**Pull request merged**
